function data = MDDvsCTRL_readTMSi(filename) 

%% PARAMETERS
EEG_CH      = 1:64; 
ECG_CH      = 65;
HEOG_CH     = 66;
VEOG_CH     = 67;
MARKER_CH   = 73;

LABELS = {'Fp1','P9','Fp2','F7','F3','Fz','F4','F8',...
    'FC5','FC1','FC2','FC6','PO9','T7','C3','Cz',...
    'C4','T8','PO10','CP5','CP1','CP2','CP6','P7',...
    'P3','Pz','P4','P8','POz','O1','Oz','O2',...
    'AF7','AF3','AF4','AF8','F5','F1','F2','F6',...
    'FC3','FCz','FC4','C5','C1','C2','C6','CP3',...
    'CPz','CP4','P5','P1','P2','P6','FT9','PO3',...
    'PO4','FT10','FT7','FT8','TP7','TP8','PO7','PO8',...
    'ECG','HEOG','VEOG','Marker'}';

 
%% LOAD DATA
temp = tms_read(filename);
 
%% GENERATE FIELDTRIP FORMAT
channels        = [EEG_CH, ECG_CH, HEOG_CH, VEOG_CH, MARKER_CH]; 
data.trial      = {cat(1,temp.data{channels})}; 
data.fsample    = temp.fs; 
data.time       = {[1:size(data.trial{1},2)]/data.fsample};
data.label      = LABELS;
    
data.hdr.Fs             = temp.header.FS;
data.hdr.nChans         = length(channels);
data.hdr.nSamples       = temp.header.NumberOfSamplePeriods;
data.hdr.nSamplesPre    = 0;
data.hdr.nTrials        = 1;
data.hdr.label          = data.label;
data.hdr.chantype       = {'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'ECG','EOG','EOG','Marker'}';
data.hdr.chanunit   = {'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','V'};

%% OPTIONAL - Reorder Channels
flipped = reverse(LABELS(1:64));
[~, b]  = sort(flipped);

data.label(1:64)        = data.label(b);
data.trial{1}(1:64,:)   = data.trial{1}(b,:);
data.hdr.label          = data.label(b);

%% OPTIONAL - Extra Info
data.hdr.measurementdate        = temp.measurementdate;
data.hdr.path                   = temp.path;
data.hdr.filename               = temp.filename;
data.hdr.measurementtime        = temp.measurementtime;
data.hdr.measurementduration    = temp.measurementduration;
