function ICA_data = MDDvsCTRL_ICAdata(interp)
% Takes input and creates concatenated file

cfg = [];

if length(interp) == 7

    ICA_data    = ft_appenddata(cfg, interp(1),...
        interp(2),...
        interp(3),...
        interp(4),...
        interp(5),...
        interp(6),...
        interp(7));
    
elseif length(interp) == 6
    
    ICA_data    = ft_appenddata(cfg, interp(1),...
        interp(2),...
        interp(3),...
        interp(4),...
        interp(5),...
        interp(6));
end

% Create event list to aid in plotting ICA components
for a = 1:length(interp)
    temp(a).trials = a*ones(1,length(interp(a).trial));
end

ICA_data.cfg.hdr.trialindex = horzcat(temp.trials);
ICA_data.cfg.hdr.triallist  = {interp.block};

